name: Commit changes
description: Commit changes action to avoid duplication
inputs:
  commit-message:
    default: 'chore: apply changes'
    description: Commit message respecting conventionnal commit
    required: true
runs:
  using: composite
  steps:
    - if: github.event_name == 'pull_request'
      name: Commit changes
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add .
        git commit -m"${{ inputs.commit-message }}" || exit 0
        git push
        exit 1
      shell: bash
    - if: github.event_name == 'push'
      name: Commit changes
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add .
        git commit -m"${{ inputs.commit-message }}" || exit 0
        git push origin main
      shell: bash
