version: 2
updates:
  - package-ecosystem: "npm"
    allow:
      - dependency-type: "direct"
    assignees:
      - "Dorianspeed"
    commit-message:
      include: scope
      prefix: "build"
    directory: "/"
    groups:
      yarn-minor-and-patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor
      yarn-major:
        applies-to: version-updates
        update-types:
          - major
    open-pull-requests-limit: 5
    reviewers:
      - "Dorianspeed"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Paris"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    assignees:
      - "Dorianspeed"
    commit-message:
      include: scope
      prefix: "build"
    directory: "/"
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor
      actions-major:
        applies-to: version-updates
        update-types:
          - major
    open-pull-requests-limit: 5
    reviewers:
      - "Dorianspeed"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Paris"