name: Install deps
description: Install deps action to avoid duplication
runs:
  using: composite
  steps:
    - name: Use Node.js and cache deps
      uses: actions/setup-node@v4
      with:
        node-version: '22.15.0'
        cache: 'yarn'
    - name: Install dependencies
      shell: bash
      run: yarn --immutable
