name: Main Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run make coverage badges
        run: yarn make-coverage-badges
      - name: Run prettier
        run: yarn prettier "README.md" --write
      - uses: ./.github/actions/commit_changes
        with:
          commit-message: 'docs: update README.md with new tests coverages'
