name: Main Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run make coverage badges
        run: yarn make-coverage-badges
