name: Main Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run make coverage badges
        run: yarn make-coverage-badges
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m"docs: update README.md with new tests coverages" || exit 0
          git push -f origin main
