name: PR Pipeline

on: pull_request

jobs:
  build:
    needs: [circular-deps, commitlint, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run build
        run: yarn build

  circular-deps:
    needs: prettify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Check circular-deps
        run: yarn circular-deps

  commitlint:
    needs: prettify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install_deps
      - name: Check conventionnal commits
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  lint:
    needs: prettify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run linter
        run: yarn eslint

  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: ./.github/actions/install_deps
      - name: Run prettier
        run: yarn prettier "./src/**/*.{ts,tsx}" --write
      - name: Get last commit author
        id: last-commit-author
        run: echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - name: Amend no edit the last commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: ${{ steps.last-commit-author.outputs.author }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true

  tests:
    needs: [circular-deps, commitlint, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run tests
        run: yarn test
