name: PR Pipeline

on: 
  pull_request:
    types: [edited, opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  build-and-tests:
    name: Circular deps / Linter / Build / Tests
    needs: [prettier, unused-deps-exports-files, sync-deps]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install dependencies
        uses: ./.github/actions/install_deps
      - name: Run circular deps
        run: yarn circular-deps
      - name: Run linter
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test

  commitlint:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    name: Conventionnal commits
    needs: [prettier, unused-deps-exports-files, sync-deps]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/install_deps
      - name: Check conventionnal commits
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  prettier:
    name: Prettier
    needs: unused-deps-exports-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_ACTIONS_PAT }}
      - name: Install dependencies
        uses: ./.github/actions/install_deps
      - name: Run prettier
        run: yarn prettier "./**/*.{ts,tsx}" --write
      - name: Commit changes
        uses: ./.github/actions/commit_changes
        with:
          commit-message: "chore: apply code formatting"

  sync-deps:
    name: Sync deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install_deps
      - name: Check for mismatching deps version
        run: yarn sync-deps

  unused-deps-exports-files:
    name: Unused deps / exports / files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_ACTIONS_PAT }}
      - name: Install dependencies
        uses: ./.github/actions/install_deps
      - name: Check for unused exports and files
        run: yarn unused-exports-and-files
      - name: Commit changes
        uses: ./.github/actions/commit_changes
        with:
          commit-message: "chore: remove unnecessary exports and files"
      - name: Check for unused deps
        run: yarn unused-deps
