name: autofix.ci # Mandatory name for autofix-ci action usage

on: pull_request

jobs:
  build-and-tests:
    name: Circular deps / Linter / Build / Tests
    needs: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: ./.github/actions/install_deps
      - name: Run circular deps
        run: yarn circular-deps
      - name: Run linter
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test

  commitlint:
    name: Conventionnal commits
    needs: prettier
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install_deps
      - name: Check conventionnal commits
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_deps
      - name: Run prettier
        run: yarn prettier "./**/*.{ts,tsx}" --write
      - name: Commit changes
        uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
        with:
          commit-message: 'chore: apply code formatting'
